"""Render the provider fault-injection matrix to docs/RESILIENCE.md.

Runs every scenario from tests/test_provider_faults.py against the real
classification chain (providers mocked) and refuses to write the document if
any result differs from the tested contract.
Usage: python -m scripts.render_fault_matrix
"""
from pathlib import Path

from tests.test_provider_faults import EXPECTED, FAULTS, run_scenario

OUTPUT = Path(__file__).resolve().parents[1] / 'docs' / 'RESILIENCE.md'
SCOPES = (('primary', 'Only the primary Gemini model fails'),
          ('all_routes', 'Every route fails (Gemini primary, Gemini fallback, Groq)'))


def render():
    lines = [
        '# Provider resilience matrix',
        '',
        'Generated by `python -m scripts.render_fault_matrix` from the tested contract in',
        '`tests/test_provider_faults.py`. Each fault is injected into the real',
        '`classify_email` chain with the provider SDKs mocked; no network calls are made.',
        '',
        'Routing rules:',
        '- A temporary failure (timeout, 429, 5xx) cools the model down and tries the next route.',
        '- A broken model (400, 404, unknown error) is cooled down, and the next route is tried.',
        '- A rejected Gemini key (401/403) skips the other Gemini models and goes to Groq.',
        '- A bad answer (not JSON, category outside the enum) tries the next route without a cooldown.',
        '- The email fails only after every route is tried. It is retried later if any route',
        '  failed temporarily; otherwise it goes to Needs Review.',
        '',
    ]
    for scope, title in SCOPES:
        lines += [f'## {title}', '',
                  '| Fault | Routes called | Outcome | Category / reason | Email result |',
                  '| --- | --- | --- | --- | --- |']
        for fault, (description, _gemini, _groq) in FAULTS.items():
            actual = run_scenario(fault, scope)
            if actual != EXPECTED[(fault, scope)]:
                raise SystemExit(f'{fault}/{scope}: {actual} != {EXPECTED[(fault, scope)]}')
            routes, outcome, detail, email = actual
            lines.append(f'| {description} | {routes} | {outcome} | `{detail}` | {email} |')
        lines.append('')
    return '\n'.join(lines)


if __name__ == '__main__':
    OUTPUT.write_text(render(), encoding='utf-8')
    print(f'wrote {OUTPUT}')
